---
title: "Artificial example"
author: "Przemyslaw Biecek"
output:
  html_document
---

# Create a dataset

```{r warning=FALSE, message=FALSE}
set.seed(13)
beta1 <- 2/3
beta2 <- 1
beta3 <- 1
beta4 <- 1
epsilon <- 1/5
N <- 100
Ntest <- 10000

library(randomForest)
library(breakDown)
library(DALEX)

x1 <- runif(N+Ntest)
x2 <- runif(N+Ntest)
x3 <- runif(N+Ntest)
x4 <- runif(N+Ntest)

y <- beta1*(abs(x1-0.5) < 0.25) +
  beta2*x2 +
  beta3*x3 +
  beta4*x4 +
  epsilon*runif(N)

df <- data.frame(y, x1, x2, x3, x4)
dfTest <- df[(1+N):(N+Ntest),]
df <- df[1:N,]
```

# Fit models, create explainers

```{r warning=FALSE, message=FALSE}
mlm <- lm(y~., df)
mrf <- randomForest(y~., df)
mlm2 <- lm(y~I(abs(x1-0.5)<0.25)+x2+x3+x4, df)
  
print(mean((predict(mlm, dfTest) - dfTest$y)^2))
print(mean((predict(mrf, dfTest) - dfTest$y)^2))

exp_ml <- DALEX::explain(mlm, data = dfTest, y = dfTest$y)
exp_rf <- DALEX::explain(mrf, data = dfTest, y = dfTest$y)
```

# Variable importance

```{r warning=FALSE, message=FALSE}
v1 <- variable_dropout(exp_ml)
v2 <- variable_dropout(exp_rf)
plot(v1, v2)
```

# Single variables

```{r warning=FALSE, message=FALSE}
library(ggplot2)
v1 <- single_variable(exp_ml, "x1")
v2 <- single_variable(exp_rf, "x1")
plot(v1, v2) +ggtitle("Variable x1")

v1 <- single_variable(exp_ml, "x2")
v2 <- single_variable(exp_rf, "x2")
plot(v1, v2) +ggtitle("Variable x2")

v1 <- single_variable(exp_ml, "x3")
v2 <- single_variable(exp_rf, "x3")
plot(v1, v2) +ggtitle("Variable x3")

v1 <- single_variable(exp_ml, "x4")
v2 <- single_variable(exp_rf, "x4")
plot(v1, v2) +ggtitle("Variable x4")
```

# Raw relations

```{r}
ggplot(df, aes(x1, y)) + geom_point() + geom_smooth(se=FALSE)
ggplot(df, aes(x2, y)) + geom_point() + geom_smooth(se=FALSE)
ggplot(df, aes(x3, y)) + geom_point() + geom_smooth(se=FALSE)
ggplot(df, aes(x4, y)) + geom_point() + geom_smooth(se=FALSE)
```

# New model

```{r warning=FALSE, message=FALSE}
mlm2 <- lm(y~I(abs(x1-0.5)<0.25)+x2+x3+x4, df)
  
print(mean((predict(mlm, dfTest) - dfTest$y)^2))
print(mean((predict(mrf, dfTest) - dfTest$y)^2))
print(mean((predict(mlm2, dfTest) - dfTest$y)^2))

exp_ml2 <- DALEX::explain(mlm2, data = dfTest, y = dfTest$y, label = "lm_new")

v1 <- variable_dropout(exp_ml)
v2 <- variable_dropout(exp_rf)
v3 <- variable_dropout(exp_ml2)
plot(v1, v2, v3)

v1 <- single_variable(exp_ml, "x1")
v2 <- single_variable(exp_rf, "x1")
v3 <- single_variable(exp_ml2, "x1")
plot(v1, v2, v3) +ggtitle("Variable x1")

```


